name: build

on: [push]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload darwin arm64
        uses: actions/upload-artifact@v3
        with:
          name: spotifydl darwin arm64
          path: dist/spotifydl_darwin_arm64/spotifydl

      - name: Upload darwin amd64
        uses: actions/upload-artifact@v3
        with:
          name: spotifydl darwin amd64
          path: dist/spotifydl_darwin_amd64_v1/spotifydl

      - name: Upload windows amd64
        uses: actions/upload-artifact@v3
        with:
          name: spotifydl windows amd64
          path: dist/spotifydl_windows_amd64_v1/spotifydl.exe